content:
  - name: chapter
    label: Chapters
    type: collection
    path: chapter
    # 👇 match MDX files
    filename: "{primary}.mdx"
    subfolders: true
    format: yaml-frontmatter

    view:
      layout: tree
      node:
        # 👇 if your folder nodes are `index.mdx`
        filename: index.mdx
        hideDirs: all
      fields: [title, "sidebar.label", "sidebar.order", lastUpdated, draft]
      primary: title
      sort: ["sidebar.order", title]
      search: [title, description]
      default: { sort: "sidebar.order", order: asc }

    fields:
      # … your other frontmatter fields …
      - name: body
        label: Content
        type: code
        options:
          language: markdown
        media: images
