# .pages.yml — PagesCMS config for learnkorean-content

media:
  - name: images
    label: Images
    input: public/media
    output: /media
    categories: [image]
  - name: files
    label: Files
    input: public/files
    output: /files
    categories: [document, audio, video, compressed]

content:
  - name: chapter
    label: Chapters
    type: collection
    path: chapter
    # 👇 match MDX files
    filename: "{primary}.mdx"
    subfolders: true
    format: yaml-frontmatter

    view:
      layout: tree
      node:
        # 👇 if your folder nodes are `index.mdx`
        filename: index.mdx
        hideDirs: all
      fields: [title, "sidebar.label", "sidebar.order", lastUpdated, draft]
      primary: title
      sort: ["sidebar.order", title]
      search: [title, description]
      default: { sort: "sidebar.order", order: asc }

    fields:
      # … your other frontmatter fields …
      - name: body
        label: Content
        type: code
        options:
          language: markdown
        media: images


components:
  sidebarBadge:
    label: Sidebar Badge
    type: object
    fields:
      - name: text
        label: Text
        type: string
      - name: variant
        label: Variant
        type: select
        options:
          values:
            - { label: Tip,     value: tip }
            - { label: Note,    value: note }
            - { label: Caution, value: caution }
            - { label: Danger,  value: danger }

settings:
  hide: false
  content:
    merge: true
